name: Elixir CI

on: [push]

jobs:

  build:
    name: build and test 

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14.3
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.13' # Define the elixir version [required]
        otp-version: '24.2' # Define the OTP version [required]
        
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: build
      run: mix compile --warnings-as-errors
 
    - name: static_analysis
      run: | 
        mix credo -a
        mix format --check-formatted

    - name: test
      run: mix coveralls

    - name: build_realise
      run: mix release
