name: Elixir CI

on: [push]

jobs:

  build:
    name: build and test 

    runs-on: ubuntu-latest
    container: bunsan/ubuntu-elixir:elixir-10_otp-24

    services:
      db:
        image: postgres:14.3
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.clean --all
        mix deps.get

    - name: build
      run: mix compile --warnings-as-errors
 
    - name: static_analysis
      run: | 
        mix credo -a
        mix format --check-formatted
    - name: test
      run: mix coveralls

    - name: build_release
      run: mix release